services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db
    restart: always

  nest-backend:
    build:
      context: ./nestjs-backend
    container_name: nest-backend
    ports:
      - "3030:3030"
    env_file:
      - ./nestjs-backend/.env
    depends_on:
      - mongo
    restart: always

  vitejs-site:
    build:
      context: ./nuitd-de-linfo-front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nuit-de-linfo-front/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Optionnel, pour personnaliser Nginx
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  mongo_data:
